---
- name: "Instala pacotes de dependências do sistema operacional"
  apt:
    name: "{{ item }}"
    cache_valid_time: 3600
    state: latest
  become: yes
  loop:
    - php5
    - apache2
    - libapache2-mod-php5
    - php5-gd
    - libssh2-php
    - php5-mcrypt
    - php5-mysql
